### ISSUE TITLE
WiFi vocabulary listing error in great book 

### ISSUE THREAD

**Issue by DavidJRichards** [MPETREMANN11/ESP32forth#2]
The listing of WiFi vocabulary in the great book V1.15 has wire entries by mistake.

![Screenshot from 2024-01-01 08-50-59](https://github.com/MPETREMANN11/ESP32forth/assets/16197914/77fd9e90-56e7-4634-b71d-db4f49c57f6f)

Seen here on page 256 of the english version, same problem in french version too.

**Comment by MPETREMANN11** [comment]
corrected

**Comment by MPETREMANN11** [comment]
closed
